ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\Users\amey9\AppData\Local\Temp\ipykernel_23932\2161487821.py", line 6, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
